repos:

  - repo: local
    hooks:
      - id: clippy
        name: clippy
        description: Lint rust sources
        entry: cargo clippy
        language: system
        args: ["--", "-D", "warnings"]
        types: [rust]
        pass_filenames: false

  - repo: local
    hooks:
      - id: cargo-test
        name: Run cargo test
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false
